### ISSUE TITLE
approve() not standards compliant

### ISSUE THREAD

**Issue by Nanolucas** [dharmaprotocol/NonFungibleToken#4]
I believe you have made a mistake in NonFungibleToken.sol in `approve()`.

According to the [latest draft of the] standard:

> A conforming contract MUST allow the current owner to "transfer" a token to themselves, as a way of affirming ownership in the event stream. (i.e. it is valid for _to == ownerOf(_tokenID).) This "no-op transfer" MUST be considered a successful transfer, and therefore MUST fire a Transfer event (with the same address for _from and _to).
>
>Important: Please refer to the Note in the approve method description; a successful transfer MUST clear pending approval. _This includes no-op transfers to the current owner!_

This would mean your line `require(msg.sender != _to);` must be removed

**Comment by nadavhollander** [comment]
Maybe I'm missing something here, but I think you're mixing up the `transfer()` and `approve()` methods.

Under the `approve()` section of the standard:

> This method MUST throw if msg.sender != ownerOf(_tokenId), or if _tokenID does not represent an NFT currently tracked by this contract, or if msg.sender == _to.

LMK if I'm having a brain fart

**Comment by Nanolucas** [comment]
It seems you're right, my apologies. I guess I had it in my head that all transfers would always go through the approve() process first, but if it's a transfer() call from the token owner then that isn't actually required.

**Comment by nadavhollander** [comment]
No worries!  Thanks for taking a look :)
