### ISSUE TITLE
Issue using `npm run migrate`

### ISSUE THREAD

**Issue by herroannekim** [dharmaprotocol/NonFungibleToken#7]
I was trying to run `npm run migrate` and got this...

"""
$ npm run transpile

> NonFungibleToken@0.0.1 transpile /Users/annekim/Documents/NonFungibleToken
> rm -rf ./transpiled; copyfiles ./build/**/* ./transpiled; tsc

test/ts/non_fungible_token.ts(6,39): error TS2307: Cannot find module '../../types/generated/test_mintable_n_f_t'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! NonFungibleToken@0.0.1 transpile: `rm -rf ./transpiled; copyfiles ./build/**/* ./transpiled; tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the NonFungibleToken@0.0.1 transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/annekim/.npm/_logs/2018-03-16T14_42_18_521Z-debug.log
"""

Halp?

**Comment by johndpope** [comment]
you could try install nvm 
https://github.com/creationix/nvm

(using iterm + zsh + oh-my-zsh here too )
https://github.com/robbyrussell/oh-my-zsh

once that's done use node version 10
**nvm install 10.0.0
nvm use 10.0.0**

(probably a good idea to work out what version of node you have installed -
**node --version**
 that way if other apps suddenly break - you can toggle down a version if need be)
![screen shot 2018-05-14 at 15 42 09](https://user-images.githubusercontent.com/289994/40019488-6233f104-578d-11e8-9240-926a40a4d43c.png)

**Comment by nadavhollander** [comment]
Hey guys -- serious apologies if this is "too-little too-late", but this repository has solidly fallen out of maintenance.  I'm marking it as deprecated and recommend people use the Zeppelin ERC721 implementation in lieu of this one.
